urls:
  login: http://linkedin.com/login
  network: https://www.linkedin.com/mynetwork/
logging:
  version: 1
  formatters:
    short:
      format: '%(levelname)s: %(message)s'
    long:
      format: '[%(asctime)s] %(levelname)s @line-%(lineno)d: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: short
      level: DEBUG
    file_handler:
      class: logging.FileHandler
      level: DEBUG
      formatter: long
      filename: info.log
      encoding: utf8
      mode: a
  root:
    level: DEBUG
    handlers: [ file_handler, console ]
